### ISSUE TITLE
Cannot read properties of undefined (reading 'reference')

### ISSUE THREAD

**Issue by thiagotsn** [1Password/op-vscode#69]
### Your environment

op-vscode version: 1.0.1

VS Code version: 1.70.2 (Apple Silicon)

CLI version: 2.6.2

OS: macOS Monterey v12.5.1

## Steps to reproduce
When using the Save in 1Password feature in the command palette or json file.

1. Select a secret 
2. ⌘+⇧+P
3. Select 1Password: Save in 1Password 
4. Enter a name: MyEntry
5. Enter field name: password
6. Use TouchID to allow 1Password 

## What happened?

A notification with: _Cannot read properties of undefined (reading 'reference')_
An entry in 1Password is created with just the title and without the secret.

## What did you expect to happen?

Saving the secret in 1Password entry.

## Notes & Logs

[2022-08-26 15:34:40.657] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'reference')
    at /Users/thiago/.vscode/extensions/1password.op-vscode-1.0.1/dist/extension.js:53:6016
    at Object.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:54197)
    at Ct.insertSavedItem (/Users/thiago/.vscode/extensions/1password.op-vscode-1.0.1/dist/extension.js:53:5994)
    at Ct.saveItem (/Users/thiago/.vscode/extensions/1password.op-vscode-1.0.1/dist/extension.js:53:4340)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /Users/thiago/.vscode/extensions/1password.op-vscode-1.0.1/dist/extension.js:53:2298
    at a._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:63914)
    at a._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:63914) op-vscode.saveValueToItem {"value":"1Password.op-vscode","_lower":"1password.op-vscode"}
[2022-08-26 15:34:40.658] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'reference')
    at /Users/thiago/.vscode/extensions/1password.op-vscode-1.0.1/dist/extension.js:53:6016
    at Object.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:54197)
    at Ct.insertSavedItem (/Users/thiago/.vscode/extensions/1password.op-vscode-1.0.1/dist/extension.js:53:5994)
    at Ct.saveItem (/Users/thiago/.vscode/extensions/1password.op-vscode-1.0.1/dist/extension.js:53:4340)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /Users/thiago/.vscode/extensions/1password.op-vscode-1.0.1/dist/extension.js:53:2298
    at a._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:63914)
    at a._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:63914) _vscode_delegate_cmd_l7akmsrm undefined

<img width="285" alt="CleanShot 2022-08-26 at 15 32 41@2x" src="https://user-images.githubusercontent.com/11219154/186929859-2d1f5563-812f-4a11-98df-b9e7b6939083.png">

**Comment by meSingh** [comment]
Also, getting this error

+1

**Comment by appetite-j** [comment]
Same here.
+1

**Comment by johnypony3** [comment]
its not useful to leave a `+1` comment but not `+1` on the actual issue. upvote the issue and it bubbles up and gets fixed quicker 🤷‍♂️.

**Comment by meSingh** [comment]
> its not useful to leave a `+1` comment but not `+1` on the actual issue. upvote the issue and it bubbles up and gets fixed quicker 🤷‍♂️.

There are only 3 open issues on this repository, are you really worried about visibility here?

**Comment by johnypony3** [comment]
its a general faux pas. are you really trying to argue on github about this?

**Comment by jodyheavener** [comment]
Hi folks, thanks for raising this issue. I haven't yet been able to identify the root cause, but I'm hoping to spend more time on it shortly here.

**Comment by jodyheavener** [comment]
Hey all, just wanted to follow up to note that I'm able to replicate this issue now, and it looks related to newer versions of the CLI. You could try downgrading to an older version in the meantime, but that's not ideal, and at any rate I'll be getting a fix out as soon as possible. I'll update this thread once a fix is out. Thanks for your patience.

**Comment by johnypony3** [comment]
thank you fir the update @jodyheavener

**Comment by jodyheavener** [comment]
v1.0.2 of the extension is rolling out now, which should address this issue. Please let me know if you continue to encounter it!
